#!/usr/bin/env bash

layout_conda() {
  envs=($(conda info --json | python3 -c "import sys, json; print('\n'.join(json.load(sys.stdin)['envs_dirs']))")) 
  echo $envs
  for env in ${envs[@]}; do
  	if [ -d $env ]; then
  		PATH_add ${env/%//$1/bin}
	fi
  done
}
